apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: spotter-ray-service
spec:
  serveConfigV2: |
    applications:
      - name: spotter-serve
        import_path: spotter.serve:deployment
        route_prefix: /detect
        deployments:
          - name: AmenitiesDetector
  rayClusterConfig:
    rayVersion: 2.44.1
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - name: ray-head
              image: {{.Image}}
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 1
                  memory: 6Gi
                limits:
                  cpu: 2
                  memory: 8Gi
              ports:
                - containerPort: 6379
                  name: gcs
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - groupName: spotter-worker
        replicas: 1
        minReplicas: 1
        maxReplicas: 5
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: {{.Image}}
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: 1
                    memory: 2Gi
                  limits:
                    cpu: 1
                    memory: 4Gi
