name: Pull request
on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SPOTTER_DIR: ./apps/spotter
  SPOTTER_MANAGER_DIR: ./apps/spotter-manager

jobs:
  python-lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          fail-mode: true

      - name: Set up Python environment
        run: nix develop --command bash -c 'uv sync --all-extras'

      - name: Ruff lint
        run: |
          nix develop --command bash -c '
            ruff --version
            ruff --config ${SPOTTER_DIR}/pyproject.toml check --show-fixes --target-version py312 ${SPOTTER_DIR}
          '

      - name: Ruff format
        run: |
          nix develop --command bash -c '
            ruff --version
            ruff --config ${SPOTTER_DIR}/pyproject.toml format --check --diff --target-version py312 ${SPOTTER_DIR}
          '

      - name: Pytest
        run: |
          nix develop --command bash -c '
            uv run pytest --version
            uv run pytest -v --color=yes ${SPOTTER_DIR}
          '

  go-lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          fail-mode: true

      - name: Set up Go environment
        run: nix develop --command bash -c 'go mod download'

      - name: Go lint
        run: |
          nix develop --command bash -c '
            golangci-lint run --fast-only ${SPOTTER_MANAGER_DIR}/...
          '

      - name: Go test
        run: nix develop --command bash -c 'go test ${SPOTTER_MANAGER_DIR}/...'
